# =====================================================================
# Flyway Configuration File - SGFrotas (Supabase Central)
# =====================================================================

flyway.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
flyway.user=postgres.eychznasujcjfdupizfm
flyway.password=Br@sil#$%2026
flyway.schemas=public
flyway.defaultSchema=public
flyway.table=flyway_schema_history

flyway.locations=filesystem:db/migrations

# Políticas de Segurança & Continuidade
flyway.baselineOnMigrate=true
flyway.baselineVersion=65
flyway.baselineDescription=DigitalTwin Baseline V65
flyway.validateOnMigrate=true
flyway.cleanDisabled=true
flyway.outOfOrder=false
flyway.mixed=true
